### ISSUE TITLE
VSIX Install failed

### ISSUE THREAD

**Issue by themobydisk** [aldobrynin/CleanBinAndObj#1]
### Installed product versions
- Visual Studio 2017 Enterprise V15.5.6
- Version 1.0?  As of 3/26/2018 10:23am Eastern

### Description
System.UriFormatException: A relative URI cannot be created because the 'uriString' parameter represents an absolute URI.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionHeaderImpl.get_License()
   at VSIXInstaller.ViewModel.ExtensionViewModel..ctor(IExtension extension, IEnumerable`1 packages, Boolean satisfied, Boolean showPackages)
   at VSIXInstaller.ViewModel.InstallableExtensionViewModel..ctor(IInstallableExtension extension, IEnumerable`1 packages, Boolean satisfied, Boolean showPackages, Boolean alreadyInstalled, Boolean isNotInstallableSDK)
   at VSIXInstaller.ViewModel.InstallableExtensionViewModel.CreateWithoutPackages(InstallExtensionData installData)
   at VSIXInstaller.SingleInstallPage..ctor(ExtensionData data, InstallExtensionData installData, IEnumerable`1 targetSkus)
   at VSIXInstaller.LoadingPage.<>c__DisplayClass11_1.<OnLoaded>b__2()

Install log attached

### Steps to recreate
1. Download CleanBinAndObj.vsix
2. Launch it
3. Visual Studio began the install
4. Visual Studio displayed the generic dialog indicating the install failed.

### Current behavior
Install did not complete successfully.

### Expected behavior
- Install should have completed
- Extension should have rocked the world.
[VSIXInstaller_e8c621ec-4b70-4212-9381-f6a297e6a12a.log](https://github.com/aldobrynin/CleanBinAndObj/files/1848188/VSIXInstaller_e8c621ec-4b70-4212-9381-f6a297e6a12a.log)

**Comment by aldobrynin** [comment]
@themobydisk, thank you for your feedback!
Please download [latest release](https://github.com/aldobrynin/CleanBinAndObj/releases/tag/1.0.19) (or via https://marketplace.visualstudio.com/items?itemName=dobrynin.cleanbinandobj, just changed link to same version). 
Something went wrong and resource icon broke installation in release 1.0.17.
Fixed this issue in 1.0.19

I hope now we will rock the world!
